config/routes.rb
Rails.application.routes.draw do
  root 'words#home'
  get '/new', to: 'words#new'
  post '/new', to: 'words#create'
  get '/index', to:'words#index'
  get '/edit', to: 'words#edit'
  put '/edit', to: 'words#update'
  resources :words
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/word.rb
class Word < ApplicationRecord
    validates :question, presence:true, length: { maximum: 100 }
    validates :answer, presence:true, length: { maximum: 100 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    def hello
        render html: "hello, world"
    end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  # Page display all words
  def index
    @words = Word.all
  end

  # Page display one word
  def show
  end

  # Page create new word
  def new
    @word = Word.new
  end

  # Page edit existing word
  def edit
    @word = Word.find(params[:id])
  end

  # top page
  def home
  end

  # POST new word
  def create
    @word = Word.new(word_params)
    if @word.save
      redirect_to index_path
    else
      render 'new'
    end
  end

  # PATCH word
  def update
    @word = Word.find(params[:id])
    if @word.update_attributes(word_params)
    redirect_to index_path
    else
      render 'edit'
    end
  end

  # DELETE word
  def destroy
    Word.find(params[:id]).destroy
    redirect_to index_path
  end

  def word_params
    params.require(:word).permit(:question, :answer, :memorize)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta charset="utf-8">
    <title><%= yield(:title )%> | Kotoba</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <div class="app-header">
      <div class="app-title">Kotoba</div>
      <div class="header-link">
        <%= link_to "Home", root_path%>
      </div>
      </div>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/words/edit.html.erb
<% provide(:title, 'Edit')%>
<div class="header-link">
<%= link_to "Word list", index_path%>
<h1 class="page-title">Edit word</h1>
<div class="word-form">
    <%= form_for(@word) do |f|%>
    <div class="text-field">
        <%= f.label :question %>
        <%= f.text_field :question %>
    </div>

    <div class="text-field">
        <%= f.label :answer %>
        <%= f.text_field :answer %>
    </div>

    <div class="text-field">
        <%= f.label :memorize %>
        <%= f.text_field :memorize %>
    </div>

    <div class="text-field">
        <%= f.submit "Save change" %>
    </div>
    <% end %>
</div>

app/views/words/home.html.erb
<% provide(:title, "Home")%>
<div class="home">
    <h1>Kotoba</h1>
    <h2>Let's learn languages!</h2>
    <div class="lanuage">
        <p>🇵🇭 <%= link_to "Tagalog", index_path%></p>
        <p>🇯🇵 Japanese</p>
        <p>🇨🇳 Chinese</p>
    </div>
</div>

app/views/words/index.html.erb
<% provide(:title, "List")%>
<div class="header-link">
<%= link_to "Add new word", new_path%>
</div>
<h1 class="page-title">All words</h1>
<% @words.each do |word|%>
<div class="word-card">
<div class="word-content">
    <div class="edit-card">
        <%= link_to "delete", word, method: :delete, data: { confirm: "Are you sure?"}%>
        <%= link_to "edit", edit_word_path(word)%>
    <% if word.memorize == 1%>
        <div>
            <%= link_to image_tag("correct.png", :width => '25', :height => '25', alt: "memorized")%>
        </div>
    <% else %>
        <div>
            <%= link_to image_tag("incorrect.png", :width => '25', :height => '25', alt: "notyet")%>
        </div>
    <% end %>
    </div>
    <p class="word-qa">English: <%= word.question %></p>
    <p class="word-qa">Tagalog: <%= word.answer %></p>
    </div>
</div>
<% end %>

app/views/words/new.html.erb
<% provide(:title, 'Add')%>
<div class="header-link">
<%= link_to "Word list", index_path%>
</div>
<h1 class="page-title">Add new word</h1>
<div class="word-form">
    <%= form_for(@word, url: new_path) do |f|%>
        <div class="text-field">
            <%= f.label :question %>
            <%= f.text_field :question %>
        </div>

        <div class="text-field">
            <%= f.label :answer %>
            <%= f.text_field :answer %>
        </div>

        <div class="text-field">
            <%= f.label :memorize %>
            <%= f.text_field :memorize %>
        </div>

        <div class="text-field">
            <%= f.submit "Create new word" %>
        </div>
    <% end %>
</div>